// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhUlSkUJR4L_7kt1ZIUphTWWMkrZbI564',
    appId: '1:511844645852:web:02370b68e337e81d17ed19',
    messagingSenderId: '511844645852',
    projectId: 'sannabi-4115d',
    authDomain: 'sannabi-4115d.firebaseapp.com',
    storageBucket: 'sannabi-4115d.firebasestorage.app',
    measurementId: 'G-VR10EMKVYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7X52Ag6_D4nfgvVfpKUa2wiOZMY0yjCk',
    appId: '1:511844645852:android:c501a1a0474d225517ed19',
    messagingSenderId: '511844645852',
    projectId: 'sannabi-4115d',
    storageBucket: 'sannabi-4115d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiKns6umEwfjt-aeJawXXj1D5ealNCBTc',
    appId: '1:511844645852:ios:3891dd02178f129717ed19',
    messagingSenderId: '511844645852',
    projectId: 'sannabi-4115d',
    storageBucket: 'sannabi-4115d.firebasestorage.app',
    androidClientId: '511844645852-9dpe0es9lqj3rm87dphvfoc1nfs7v0u2.apps.googleusercontent.com',
    iosClientId: '511844645852-5o3ssntosglc7io8hgjc9am6apha5u6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.sannavi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiKns6umEwfjt-aeJawXXj1D5ealNCBTc',
    appId: '1:511844645852:ios:3891dd02178f129717ed19',
    messagingSenderId: '511844645852',
    projectId: 'sannabi-4115d',
    storageBucket: 'sannabi-4115d.firebasestorage.app',
    androidClientId: '511844645852-9dpe0es9lqj3rm87dphvfoc1nfs7v0u2.apps.googleusercontent.com',
    iosClientId: '511844645852-5o3ssntosglc7io8hgjc9am6apha5u6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.sannavi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhUlSkUJR4L_7kt1ZIUphTWWMkrZbI564',
    appId: '1:511844645852:web:0bfb73211a9808f517ed19',
    messagingSenderId: '511844645852',
    projectId: 'sannabi-4115d',
    authDomain: 'sannabi-4115d.firebaseapp.com',
    storageBucket: 'sannabi-4115d.firebasestorage.app',
    measurementId: 'G-G0NERQQPZM',
  );
}
